#!/usr/bin/env php
<?php

use Configuration\Config;
use Router\Command;

require_once 'vendor/autoload.php';

require_once getRoutesFile(Config::get('app.RoutesFile'));

$commandNamespace = Config::get('app.CommandNamespace');
$commandDirectory = __DIR__ . Config::get('app.CommandDirectory');

Command::registerAllCommands($commandNamespace, $commandDirectory);

$command =  $argv[1] ?? null;
$argument = $argv[2] ?? null;

if($command){
    Command::run($command, $argument);
}else{
    throw new RuntimeException ("Command not found.\n");
}