#!/usr/bin/env php
<?php

use Router\Command;

require_once 'vendor/autoload.php';
require_once 'index.php';

$commandNamespace = 'Router\\Commands';
$commandDirectory = __DIR__ . '/src/Router/Commands';

Command::registerAllCommands($commandNamespace, $commandDirectory);

$command =  $argv[1] ?? null;
$argument = $argv[2] ?? null;

if($command){
    Command::run($command, $argument);
}else{
    echo "Command not found.\n";
}